<h2>1. PREPROCESSED_DATA</h2>

In [2]:
import pandas as pd

<h5>First 5 rows</h5>

In [15]:
df       = pd.read_csv("preprocessed_data.csv")
head  = df.head(5)
head

,Winner,title_bout,no_of_rounds,B_current_lose_streak,B_current_win_streak,B_draw,B_avg_BODY_att,B_avg_BODY_landed,B_avg_CLINCH_att,B_avg_CLINCH_landed,...,weight_class_Women's Strawweight,B_Stance_Open Stance,B_Stance_Orthodox,B_Stance_Sideways,B_Stance_Southpaw,B_Stance_Switch,R_Stance_Open Stance,R_Stance_Orthodox,R_Stance_Southpaw,R_Stance_Switch
0,Red,True,5,0.0,4.0,0.0,9.200000,6.000000,0.200000,0.000000,...,0,0,1,0,0,0,0,1,0,0
1,Red,True,5,0.0,3.0,0.0,14.600000,9.100000,11.800000,7.300000,...,0,0,1,0,0,0,0,0,1,0
2,Red,False,3,0.0,3.0,0.0,15.354839,11.322581,6.741935,4.387097,...,0,0,1,0,0,0,0,1,0,0
3,Blue,False,3,0.0,4.0,0.0,17.000000,14.000000,13.750000,11.000000,...,0,0,0,0,0,1,0,1,0,0
4,Blue,False,3,0.0,1.0,0.0,17.000000,14.500000,2.500000,2.000000,...,0,0,0,0,1,0,0,0,1,0

<h5>Last 5 rows</h5>

In [16]:
tail = df.tail(5)
tail

,Winner,title_bout,no_of_rounds,B_current_lose_streak,B_current_win_streak,B_draw,B_avg_BODY_att,B_avg_BODY_landed,B_avg_CLINCH_att,B_avg_CLINCH_landed,...,weight_class_Women's Strawweight,B_Stance_Open Stance,B_Stance_Orthodox,B_Stance_Sideways,B_Stance_Southpaw,B_Stance_Switch,R_Stance_Open Stance,R_Stance_Orthodox,R_Stance_Southpaw,R_Stance_Switch
3587,Red,False,1,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0,0,0,0,1,0,0,0,1,0
3588,Red,False,1,0.0,1.0,0.0,0.0,0.0,1.0,1.0,...,0,0,1,0,0,0,0,1,0,0
3589,Red,True,1,0.0,2.0,0.0,0.5,0.5,0.0,0.0,...,0,0,1,0,0,0,0,0,1,0
3590,Red,False,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0,0,1,0,0,0,0,0,1,0
3591,Red,False,1,0.0,1.0,0.0,4.0,3.0,9.0,4.0,...,0,0,1,0,0,0,0,1,0,0

<h5>Dataset Columns</h5>

In [48]:
cols = df.columns
print("Colums in the dataset:")
for col in cols:
    print(f" ~{col}")

<h5>Getting the data shape</h5>

In [24]:
print("The shape of the data is", df.shape)

The shape of the data is (3592, 160)

<h5>Getting the forth row of the dataset</h5>

In [38]:
# The forth row
index_4 = df.iloc[3:4]
index_4

,Winner,title_bout,no_of_rounds,B_current_lose_streak,B_current_win_streak,B_draw,B_avg_BODY_att,B_avg_BODY_landed,B_avg_CLINCH_att,B_avg_CLINCH_landed,...,weight_class_Women's Strawweight,B_Stance_Open Stance,B_Stance_Orthodox,B_Stance_Sideways,B_Stance_Southpaw,B_Stance_Switch,R_Stance_Open Stance,R_Stance_Orthodox,R_Stance_Southpaw,R_Stance_Switch
3,Blue,False,3,0.0,4.0,0.0,17.0,14.0,13.75,11.0,...,0,0,0,0,0,1,0,1,0,0

<h5>Statistical Summary of the data</h5>

In [17]:
df.describe()

,no_of_rounds,B_current_lose_streak,B_current_win_streak,B_draw,B_avg_BODY_att,B_avg_BODY_landed,B_avg_CLINCH_att,B_avg_CLINCH_landed,B_avg_DISTANCE_att,B_avg_DISTANCE_landed,...,weight_class_Women's Strawweight,B_Stance_Open Stance,B_Stance_Orthodox,B_Stance_Sideways,B_Stance_Southpaw,B_Stance_Switch,R_Stance_Open Stance,R_Stance_Orthodox,R_Stance_Southpaw,R_Stance_Switch
count,3592.000000,3592.000000,3592.000000,3592.0,3592.000000,3592.000000,3592.000000,3592.000000,3592.000000,3592.000000,...,3592.000000,3592.000000,3592.000000,3592.000000,3592.000000,3592.000000,3592.000000,3592.000000,3592.000000,3592.000000
mean,3.196548,0.560412,1.126114,0.0,8.800322,6.158010,8.308673,5.615597,53.926193,19.667738,...,0.027283,0.001392,0.768931,0.000557,0.197383,0.031737,0.003341,0.758352,0.210746,0.027561
std,0.664834,0.790660,1.385555,0.0,7.099821,5.077738,7.518370,5.415420,41.194737,16.027255,...,0.162929,0.037288,0.421575,0.023593,0.398079,0.175324,0.057711,0.428142,0.407895,0.163735
min,1.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,0.000000,0.000000,0.0,3.666667,2.500000,3.000000,2.000000,23.000000,8.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
50%,3.000000,0.000000,1.000000,0.0,7.000000,5.000000,6.467611,4.275253,45.422619,15.572727,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
75%,3.000000,1.000000,2.000000,0.0,12.275974,8.500000,11.500000,7.857143,74.723214,27.513889,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
max,5.000000,6.000000,12.000000,0.0,49.000000,39.000000,87.000000,68.000000,271.000000,130.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

<h5>Outliers</h5>
<p>Most of the columns in the dataset contains outlying values</p>

<h5>Checking for missing values</h5>

In [86]:
missing_data = df.isnull()

for column in missing_data.columns.values.tolist():
    print("\n", column)
    print (missing_data[column].value_counts())

 Winner
False    3592
Name: Winner, dtype: int64

 title_bout
False    3592
Name: title_bout, dtype: int64

 no_of_rounds
False    3592
Name: no_of_rounds, dtype: int64

 B_current_lose_streak
False    3592
Name: B_current_lose_streak, dtype: int64

 B_current_win_streak
False    3592
Name: B_current_win_streak, dtype: int64

 B_draw
False    3592
Name: B_draw, dtype: int64

 B_avg_BODY_att
False    3592
Name: B_avg_BODY_att, dtype: int64

 B_avg_BODY_landed
False    3592
Name: B_avg_BODY_landed, dtype: int64

 B_avg_CLINCH_att
False    3592
Name: B_avg_CLINCH_att, dtype: int64

 B_avg_CLINCH_landed
False    3592
Name: B_avg_CLINCH_landed, dtype: int64

 B_avg_DISTANCE_att
False    3592
Name: B_avg_DISTANCE_att, dtype: int64

 B_avg_DISTANCE_landed
False    3592
Name: B_avg_DISTANCE_landed, dtype: int64

 B_avg_GROUND_att
False    3592
Name: B_avg_GROUND_att, dtype: int64

 B_avg_GROUND_landed
False    3592
Name: B_avg_GROUND_landed, dtype: int64

 B_avg_HEAD_att
False    3592
Name: B_avg_HEAD_att, dtype: int64

 B_avg_HEAD_landed
False    3592
Name: B_avg_HEAD_landed, dtype: int64

 B_avg_KD
False    3592
Name: B_avg_KD, dtype: int64

 B_avg_LEG_att
False    3592
Name: B_avg_LEG_att, dtype: int64

 B_avg_LEG_landed
False    3592
Name: B_avg_LEG_landed, dtype: int64

 B_avg_PASS
False    3592
Name: B_avg_PASS, dtype: int64

 B_avg_REV
False    3592
Name: B_avg_REV, dtype: int64

 B_avg_SIG_STR_att
False    3592
Name: B_avg_SIG_STR_att, dtype: int64

 B_avg_SIG_STR_landed
False    3592
Name: B_avg_SIG_STR_landed, dtype: int64

 B_avg_SIG_STR_pct
False    3592
Name: B_avg_SIG_STR_pct, dtype: int64

 B_avg_SUB_ATT
False    3592
Name: B_avg_SUB_ATT, dtype: int64

 B_avg_TD_att
False    3592
Name: B_avg_TD_att, dtype: int64

 B_avg_TD_landed
False    3592
Name: B_avg_TD_landed, dtype: int64

 B_avg_TD_pct
False    3592
Name: B_avg_TD_pct, dtype: int64

 B_avg_TOTAL_STR_att
False    3592
Name: B_avg_TOTAL_STR_att, dtype: int64

 B_avg_TOTAL_STR_landed
False    3592
Name: B_avg_TOTAL_STR_landed, dtype: int64

 B_longest_win_streak
False    3592
Name: B_longest_win_streak, dtype: int64

 B_losses
False    3592
Name: B_losses, dtype: int64

 B_avg_opp_BODY_att
False    3592
Name: B_avg_opp_BODY_att, dtype: int64

 B_avg_opp_BODY_landed
False    3592
Name: B_avg_opp_BODY_landed, dtype: int64

 B_avg_opp_CLINCH_att
False    3592
Name: B_avg_opp_CLINCH_att, dtype: int64

 B_avg_opp_CLINCH_landed
False    3592
Name: B_avg_opp_CLINCH_landed, dtype: int64

 B_avg_opp_DISTANCE_att
False    3592
Name: B_avg_opp_DISTANCE_att, dtype: int64

 B_avg_opp_DISTANCE_landed
False    3592
Name: B_avg_opp_DISTANCE_landed, dtype: int64

 B_avg_opp_GROUND_att
False    3592
Name: B_avg_opp_GROUND_att, dtype: int64

 B_avg_opp_GROUND_landed
False    3592
Name: B_avg_opp_GROUND_landed, dtype: int64

 B_avg_opp_HEAD_att
False    3592
Name: B_avg_opp_HEAD_att, dtype: int64

 B_avg_opp_HEAD_landed
False    3592
Name: B_avg_opp_HEAD_landed, dtype: int64

 B_avg_opp_KD
False    3592
Name: B_avg_opp_KD, dtype: int64

 B_avg_opp_LEG_att
False    3592
Name: B_avg_opp_LEG_att, dtype: int64

 B_avg_opp_LEG_landed
False    3592
Name: B_avg_opp_LEG_landed, dtype: int64

 B_avg_opp_PASS
False    3592
Name: B_avg_opp_PASS, dtype: int64

 B_avg_opp_REV
False    3592
Name: B_avg_opp_REV, dtype: int64

 B_avg_opp_SIG_STR_att
False    3592
Name: B_avg_opp_SIG_STR_att, dtype: int64

 B_avg_opp_SIG_STR_landed
False    3592
Name: B_avg_opp_SIG_STR_landed, dtype: int64

 B_avg_opp_SIG_STR_pct
False    3592
Name: B_avg_opp_SIG_STR_pct, dtype: int64

 B_avg_opp_SUB_ATT
False    3592
Name: B_avg_opp_SUB_ATT, dtype: int64

 B_avg_opp_TD_att
False    3592
Name: B_avg_opp_TD_att, dtype: int64

 B_avg_opp_TD_landed
False    3592
Name: B_avg_opp_TD_landed, dtype: int64

 B_avg_opp_TD_pct
False    3592
Name: B_avg_opp_TD_pct, dtype: int64

 B_avg_opp_TOTAL_STR_att
False    3592
Name: B_avg_opp_TOTAL_STR_att, dtype: int64

 B_avg_opp_TOTAL_STR_landed
False    3592
Name: B_avg_opp_TOTAL_STR_landed, dtype: int64

 B_total_rounds_fought
False    3592
Name: B_total_rounds_fought, dtype: int64

 B_total_time_fought(seconds)
False    3592
Name: B_total_time_fought(seconds), dtype: int64

 B_total_title_bouts
False    3592
Name: B_total_title_bouts, dtype: int64

 B_win_by_Decision_Majority
False    3592
Name: B_win_by_Decision_Majority, dtype: int64

 B_win_by_Decision_Split
False    3592
Name: B_win_by_Decision_Split, dtype: int64

 B_win_by_Decision_Unanimous
False    3592
Name: B_win_by_Decision_Unanimous, dtype: int64

 B_win_by_KO/TKO
False    3592
Name: B_win_by_KO/TKO, dtype: int64

 B_win_by_Submission
False    3592
Name: B_win_by_Submission, dtype: int64

 B_win_by_TKO_Doctor_Stoppage
False    3592
Name: B_win_by_TKO_Doctor_Stoppage, dtype: int64

 B_wins
False    3592
Name: B_wins, dtype: int64

 B_Height_cms
False    3592
Name: B_Height_cms, dtype: int64

 B_Reach_cms
False    3592
Name: B_Reach_cms, dtype: int64

 B_Weight_lbs
False    3592
Name: B_Weight_lbs, dtype: int64

 R_current_lose_streak
False    3592
Name: R_current_lose_streak, dtype: int64

 R_current_win_streak
False    3592
Name: R_current_win_streak, dtype: int64

 R_draw
False    3592
Name: R_draw, dtype: int64

 R_avg_BODY_att
False    3592
Name: R_avg_BODY_att, dtype: int64

 R_avg_BODY_landed
False    3592
Name: R_avg_BODY_landed, dtype: int64

 R_avg_CLINCH_att
False    3592
Name: R_avg_CLINCH_att, dtype: int64

 R_avg_CLINCH_landed
False    3592
Name: R_avg_CLINCH_landed, dtype: int64

 R_avg_DISTANCE_att
False    3592
Name: R_avg_DISTANCE_att, dtype: int64

 R_avg_DISTANCE_landed
False    3592
Name: R_avg_DISTANCE_landed, dtype: int64

 R_avg_GROUND_att
False    3592
Name: R_avg_GROUND_att, dtype: int64

 R_avg_GROUND_landed
False    3592
Name: R_avg_GROUND_landed, dtype: int64

 R_avg_HEAD_att
False    3592
Name: R_avg_HEAD_att, dtype: int64

 R_avg_HEAD_landed
False    3592
Name: R_avg_HEAD_landed, dtype: int64

 R_avg_KD
False    3592
Name: R_avg_KD, dtype: int64

 R_avg_LEG_att
False    3592
Name: R_avg_LEG_att, dtype: int64

 R_avg_LEG_landed
False    3592
Name: R_avg_LEG_landed, dtype: int64

 R_avg_PASS
False    3592
Name: R_avg_PASS, dtype: int64

 R_avg_REV
False    3592
Name: R_avg_REV, dtype: int64

 R_avg_SIG_STR_att
False    3592
Name: R_avg_SIG_STR_att, dtype: int64

 R_avg_SIG_STR_landed
False    3592
Name: R_avg_SIG_STR_landed, dtype: int64

 R_avg_SIG_STR_pct
False    3592
Name: R_avg_SIG_STR_pct, dtype: int64

 R_avg_SUB_ATT
False    3592
Name: R_avg_SUB_ATT, dtype: int64

 R_avg_TD_att
False    3592
Name: R_avg_TD_att, dtype: int64

 R_avg_TD_landed
False    3592
Name: R_avg_TD_landed, dtype: int64

 R_avg_TD_pct
False    3592
Name: R_avg_TD_pct, dtype: int64

 R_avg_TOTAL_STR_att
False    3592
Name: R_avg_TOTAL_STR_att, dtype: int64

 R_avg_TOTAL_STR_landed
False    3592
Name: R_avg_TOTAL_STR_landed, dtype: int64

 R_longest_win_streak
False    3592
Name: R_longest_win_streak, dtype: int64

 R_losses
False    3592
Name: R_losses, dtype: int64

 R_avg_opp_BODY_att
False    3592
Name: R_avg_opp_BODY_att, dtype: int64

 R_avg_opp_BODY_landed
False    3592
Name: R_avg_opp_BODY_landed, dtype: int64

 R_avg_opp_CLINCH_att
False    3592
Name: R_avg_opp_CLINCH_att, dtype: int64

 R_avg_opp_CLINCH_landed
False    3592
Name: R_avg_opp_CLINCH_landed, dtype: int64

 R_avg_opp_DISTANCE_att
False    3592
Name: R_avg_opp_DISTANCE_att, dtype: int64

 R_avg_opp_DISTANCE_landed
False    3592
Name: R_avg_opp_DISTANCE_landed, dtype: int64

 R_avg_opp_GROUND_att
False    3592
Name: R_avg_opp_GROUND_att, dtype: int64

 R_avg_opp_GROUND_landed
False    3592
Name: R_avg_opp_GROUND_landed, dtype: int64

 R_avg_opp_HEAD_att
False    3592
Name: R_avg_opp_HEAD_att, dtype: int64

 R_avg_opp_HEAD_landed
False    3592
Name: R_avg_opp_HEAD_landed, dtype: int64

 R_avg_opp_KD
False    3592
Name: R_avg_opp_KD, dtype: int64

 R_avg_opp_LEG_att
False    3592
Name: R_avg_opp_LEG_att, dtype: int64

 R_avg_opp_LEG_landed
False    3592
Name: R_avg_opp_LEG_landed, dtype: int64

 R_avg_opp_PASS
False    3592
Name: R_avg_opp_PASS, dtype: int64

 R_avg_opp_REV
False    3592
Name: R_avg_opp_REV, dtype: int64

 R_avg_opp_SIG_STR_att
False    3592
Name: R_avg_opp_SIG_STR_att, dtype: int64

 R_avg_opp_SIG_STR_landed
False    3592
Name: R_avg_opp_SIG_STR_landed, dtype: int64

 R_avg_opp_SIG_STR_pct
False    3592
Name: R_avg_opp_SIG_STR_pct, dtype: int64

 R_avg_opp_SUB_ATT
False    3592
Name: R_avg_opp_SUB_ATT, dtype: int64

 R_avg_opp_TD_att
False    3592
Name: R_avg_opp_TD_att, dtype: int64

 R_avg_opp_TD_landed
False    3592
Name: R_avg_opp_TD_landed, dtype: int64

 R_avg_opp_TD_pct
False    3592
Name: R_avg_opp_TD_pct, dtype: int64

 R_avg_opp_TOTAL_STR_att
False    3592
Name: R_avg_opp_TOTAL_STR_att, dtype: int64

 R_avg_opp_TOTAL_STR_landed
False    3592
Name: R_avg_opp_TOTAL_STR_landed, dtype: int64

 R_total_rounds_fought

False    3592
Name: R_total_rounds_fought, dtype: int64

 R_total_time_fought(seconds)
False    3592
Name: R_total_time_fought(seconds), dtype: int64

 R_total_title_bouts
False    3592
Name: R_total_title_bouts, dtype: int64

 R_win_by_Decision_Majority
False    3592
Name: R_win_by_Decision_Majority, dtype: int64

 R_win_by_Decision_Split
False    3592
Name: R_win_by_Decision_Split, dtype: int64

 R_win_by_Decision_Unanimous
False    3592
Name: R_win_by_Decision_Unanimous, dtype: int64

 R_win_by_KO/TKO
False    3592
Name: R_win_by_KO/TKO, dtype: int64

 R_win_by_Submission
False    3592
Name: R_win_by_Submission, dtype: int64

 R_win_by_TKO_Doctor_Stoppage
False    3592
Name: R_win_by_TKO_Doctor_Stoppage, dtype: int64

 R_wins
False    3592
Name: R_wins, dtype: int64

 R_Height_cms
False    3592
Name: R_Height_cms, dtype: int64

 R_Reach_cms
False    3592
Name: R_Reach_cms, dtype: int64

 R_Weight_lbs
False    3592
Name: R_Weight_lbs, dtype: int64

 B_age
False    3592
Name: B_age, dtype: int64

 R_age
False    3592
Name: R_age, dtype: int64

 weight_class_Bantamweight
False    3592
Name: weight_class_Bantamweight, dtype: int64

 weight_class_Catch Weight
False    3592
Name: weight_class_Catch Weight, dtype: int64

 weight_class_Featherweight
False    3592
Name: weight_class_Featherweight, dtype: int64

 weight_class_Flyweight
False    3592
Name: weight_class_Flyweight, dtype: int64

 weight_class_Heavyweight
False    3592
Name: weight_class_Heavyweight, dtype: int64

 weight_class_Light Heavyweight
False    3592
Name: weight_class_Light Heavyweight, dtype: int64

 weight_class_Lightweight
False    3592
Name: weight_class_Lightweight, dtype: int64

 weight_class_Middleweight
False    3592
Name: weight_class_Middleweight, dtype: int64

 weight_class_Open Weight
False    3592
Name: weight_class_Open Weight, dtype: int64

 weight_class_Welterweight
False    3592
Name: weight_class_Welterweight, dtype: int64

 weight_class_Women's Bantamweight
False    3592
Name: weight_class_Women's Bantamweight, dtype: int64

 weight_class_Women's Featherweight
False    3592
Name: weight_class_Women's Featherweight, dtype: int64

 weight_class_Women's Flyweight
False    3592
Name: weight_class_Women's Flyweight, dtype: int64

 weight_class_Women's Strawweight
False    3592
Name: weight_class_Women's Strawweight, dtype: int64

 B_Stance_Open Stance
False    3592
Name: B_Stance_Open Stance, dtype: int64

 B_Stance_Orthodox
False    3592
Name: B_Stance_Orthodox, dtype: int64

 B_Stance_Sideways
False    3592
Name: B_Stance_Sideways, dtype: int64

 B_Stance_Southpaw
False    3592
Name: B_Stance_Southpaw, dtype: int64

 B_Stance_Switch
False    3592
Name: B_Stance_Switch, dtype: int64

 R_Stance_Open Stance
False    3592
Name: R_Stance_Open Stance, dtype: int64

 R_Stance_Orthodox
False    3592
Name: R_Stance_Orthodox, dtype: int64

 R_Stance_Southpaw
False    3592
Name: R_Stance_Southpaw, dtype: int64

 R_Stance_Switch
False    3592
Name: R_Stance_Switch, dtype: int64


THIS DATA HAS NO MISSING VALUES

<h5>Correlation</h5>

In [61]:
df.corr(method = "pearson").head(10)

,title_bout,no_of_rounds,B_current_lose_streak,B_current_win_streak,B_draw,B_avg_BODY_att,B_avg_BODY_landed,B_avg_CLINCH_att,B_avg_CLINCH_landed,B_avg_DISTANCE_att,...,weight_class_Women's Strawweight,B_Stance_Open Stance,B_Stance_Orthodox,B_Stance_Sideways,B_Stance_Southpaw,B_Stance_Switch,R_Stance_Open Stance,R_Stance_Orthodox,R_Stance_Southpaw,R_Stance_Switch
title_bout,1.000000,0.637445,-0.143853,0.316009,NaN,-0.006543,0.006808,0.003882,0.007960,-0.019275,...,0.013594,0.018755,-0.010486,-0.006525,0.007265,0.005609,-0.016004,-0.000962,-0.004626,0.019679
no_of_rounds,0.637445,1.000000,-0.107887,0.302900,NaN,0.080438,0.088073,0.045107,0.049887,0.085152,...,0.007040,0.011427,-0.019737,-0.077993,0.028039,-0.008138,-0.017118,0.002547,0.010488,-0.026754
B_current_lose_streak,-0.143853,-0.107887,1.000000,-0.576231,NaN,-0.037919,-0.058263,-0.040125,-0.050812,0.001552,...,-0.027930,-0.017021,0.026018,-0.001804,-0.016220,-0.021871,0.044399,0.004473,-0.025241,0.035534
B_current_win_streak,0.316009,0.302900,-0.576231,1.000000,NaN,0.043472,0.053080,0.016529,0.023525,0.026867,...,-0.010312,0.018161,-0.030190,-0.002149,0.013423,0.038544,-0.022683,0.004913,0.009131,-0.027601
B_draw,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B_avg_BODY_att,-0.006543,0.080438,-0.037919,0.043472,NaN,1.000000,0.957379,0.553233,0.553496,0.654714,...,0.197997,-0.008918,0.024180,-0.027321,-0.006927,-0.036841,-0.012870,0.012728,-0.008364,-0.007909
B_avg_BODY_landed,0.006808,0.088073,-0.058263,0.053080,NaN,0.957379,1.000000,0.602425,0.624166,0.567344,...,0.177954,-0.005119,0.024109,-0.027854,-0.010101,-0.030199,-0.012374,0.009437,-0.005147,-0.007492
B_avg_CLINCH_att,0.003882,0.045107,-0.040125,0.016529,NaN,0.553233,0.602425,1.000000,0.968278,0.292545,...,0.185550,-0.002243,0.048483,-0.020070,-0.024550,-0.057661,0.020408,0.011874,-0.008803,-0.016312
B_avg_CLINCH_landed,0.007960,0.049887,-0.050812,0.023525,NaN,0.553496,0.624166,0.968278,1.000000,0.249736,...,0.178824,-0.008480,0.052661,-0.019393,-0.027587,-0.059575,0.011371,0.011075,-0.007442,-0.014429
B_avg_DISTANCE_att,-0.019275,0.085152,0.001552,0.026867,NaN,0.654714,0.567344,0.292545,0.249736,1.000000,...,0.158766,-0.007366,0.051315,-0.027034,-0.032496,-0.044401,-0.022501,0.007457,-0.002719,-0.004795

<h5>Save cleaned data</h5>

In [85]:
df.to_csv(r"C:\Users\Nnebue Chinedu D\Desktop\dscunilag\Desmond_Nnebue_Week2\processed_preprocessed_data.csv")

<h2>2. RAW FIGHTER DATA</h2>

<h5>First 5 rows</h5>

In [3]:
data = pd.read_csv("raw_fighter_details.csv")
data.head(5)

  fighter_name  Height    Weight Reach Stance  DOB
0   AJ Fonseca   5' 4"  145 lbs.   NaN    NaN  NaN
1  AJ Matthews  5' 11"  185 lbs.   NaN    NaN  NaN
2     AJ McKee  5' 10"  145 lbs.   NaN    NaN  NaN
3    AJ Siscoe   5' 7"  135 lbs.   NaN    NaN  NaN
4   Aalon Cruz   6' 0"  145 lbs.   NaN    NaN  NaN

<h5>Last 5 rows</h5>

In [4]:
data.tail(5)

          fighter_name  Height    Weight Reach    Stance           DOB
3308     Zelim Imadaev   6' 0"  170 lbs.   76"  Orthodox  Jan 25, 1995
3309      Zhang Lipeng  5' 11"  155 lbs.   71"  Southpaw  Mar 10, 1990
3310     Zoila Frausto   5' 4"  135 lbs.   NaN  Orthodox           NaN
3311        Zu Anyanwu   6' 1"  251 lbs.   77"  Orthodox  Aug 05, 1981
3312  Zubaira Tukhugov   5' 8"  145 lbs.   68"  Orthodox  Jan 15, 1991

<h5>Dataset Columns</h5>

In [91]:
raw = data.columns
print("Colums in the dataset:")
for col in raw:
    print(f" ~{col}")

Colums in the dataset:
 ~fighter_name
 ~Height
 ~Weight
 ~Reach
 ~Stance
 ~DOB

<h5>Shape of data</h5>

In [5]:
data.shape

(3313, 6)

<h5>Fourth row</h5>

In [10]:
#The forth index
index__4 = data.iloc[3:4]
index__4

  fighter_name Height    Weight Reach Stance  DOB
3    AJ Siscoe  5' 7"  135 lbs.   NaN    NaN  NaN

<h5>Statistical summary</h5>

In [35]:
data.describe()

          fighter_name Height    Weight Reach    Stance           DOB
count             3313   3050      3238  1569      2439          2573
unique            3313     27       108    25         5          2217
top     Ericka Almeida  6' 0"  170 lbs.   72"  Orthodox  Aug 08, 1988
freq                 1    389       522   159      1913             4

No outliers as the data values are objects hence no statistical calulations were made

<h5>Dealing with missing values</h5>

In [54]:
no_value = data.isnull()
no_value.head()

   fighter_name  Height  Weight  Reach  Stance    DOB
0         False   False   False  False   False  False
1         False   False   False  False   False  False
2         False   False   False  False   False  False
3         False   False   False  False   False  False
4         False   False   False  False   False  False

In [55]:
for val in no_value.columns.values.tolist():
    print(f"\n{val}")
    print(f"{no_value[val].value_counts()}")

fighter_name
False    1485
Name: fighter_name, dtype: int64

Height
False    1485
Name: Height, dtype: int64

Weight
False    1485
Name: Weight, dtype: int64

Reach
False    1485
Name: Reach, dtype: int64

Stance
False    1485
Name: Stance, dtype: int64

DOB
False    1485
Name: DOB, dtype: int64

In [56]:
#I have decided to remove the fighters without date of birth because we cannot assume a date of birth for them
#I also dropped the missing values in weight, reach, height and stance because they're also data that are unique to every individual fighter
data.dropna(subset=["DOB", "Height", "Reach", "Weight", "Stance"], axis=0, inplace=True)

# resetting index after dropping
data.reset_index(drop=True, inplace=True)
data.head(10)

           fighter_name  Height    Weight Reach    Stance           DOB
0        Aaron Phillips   5' 9"  135 lbs.   70"  Southpaw  Aug 05, 1989
1           Aaron Riley   5' 8"  155 lbs.   69"  Southpaw  Dec 09, 1980
2            Aaron Rosa   6' 4"  205 lbs.   78"  Orthodox  May 28, 1983
3         Aaron Simpson   6' 0"  170 lbs.   73"  Orthodox  Jul 20, 1974
4  Abdul Razak Alhassan  5' 10"  170 lbs.   73"  Orthodox  Aug 11, 1985
5    Abdul-Kerim Edilov   6' 2"  205 lbs.   78"  Orthodox  Nov 25, 1991
6         Abel Trujillo   5' 8"  155 lbs.   70"  Orthodox  Sep 18, 1983
7           Abu Azaitar   5' 9"  185 lbs.   76"  Orthodox  Mar 10, 1986
8          Adam Antolin   5' 5"  125 lbs.   63"  Orthodox  Feb 28, 1982
9           Adam Hunter   6' 1"  185 lbs.   73"  Orthodox  Oct 16, 1983

<h5>Saving the data</h5>

In [59]:
data.to_csv(r"C:\Users\Nnebue Chinedu D\Desktop\dscunilag\Desmond_Nnebue_Week2\processed_raw_fighter_details.csv")

<h2>3. Raw Total Flight Data</h2>

<h5>First 5 rows</h5>

In [89]:
fight_df = pd.read_csv("raw_total_fight_data.csv", sep = ";")
fight_df.head(5)

,R_fighter,B_fighter,R_KD,B_KD,R_SIG_STR.,B_SIG_STR.,R_SIG_STR_pct,B_SIG_STR_pct,R_TOTAL_STR.,B_TOTAL_STR.,...,B_GROUND,win_by,last_round,last_round_time,Format,Referee,date,location,Fight_type,Winner
0,Henry Cejudo,Marlon Moraes,0,0,90 of 171,57 of 119,52%,47%,99 of 182,59 of 121,...,1 of 1,KO/TKO,3,4:51,5 Rnd (5-5-5-5-5),Marc Goddard,"June 08, 2019","Chicago, Illinois, USA",UFC Bantamweight Title Bout,Henry Cejudo
1,Valentina Shevchenko,Jessica Eye,1,0,8 of 11,2 of 12,72%,16%,37 of 40,42 of 52,...,0 of 0,KO/TKO,2,0:26,5 Rnd (5-5-5-5-5),Robert Madrigal,"June 08, 2019","Chicago, Illinois, USA",UFC Women's Flyweight Title Bout,Valentina Shevchenko
2,Tony Ferguson,Donald Cerrone,0,0,104 of 200,68 of 185,52%,36%,104 of 200,68 of 185,...,0 of 0,TKO - Doctor's Stoppage,2,5:00,3 Rnd (5-5-5),Dan Miragliotta,"June 08, 2019","Chicago, Illinois, USA",Lightweight Bout,Tony Ferguson
3,Jimmie Rivera,Petr Yan,0,2,73 of 192,56 of 189,38%,29%,76 of 195,58 of 192,...,4 of 10,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Kevin MacDonald,"June 08, 2019","Chicago, Illinois, USA",Bantamweight Bout,Petr Yan
4,Tai Tuivasa,Blagoy Ivanov,0,1,64 of 144,73 of 123,44%,59%,66 of 146,81 of 131,...,6 of 6,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Dan Miragliotta,"June 08, 2019","Chicago, Illinois, USA",Heavyweight Bout,Blagoy Ivanov

<h5>Last 5 rows</h5>

In [73]:
fight_df.tail(5)

,R_fighter,B_fighter,R_KD,B_KD,R_SIG_STR.,B_SIG_STR.,R_SIG_STR_pct,B_SIG_STR_pct,R_TOTAL_STR.,B_TOTAL_STR.,...,B_GROUND,win_by,last_round,last_round_time,Format,Referee,date,location,Fight_type,Winner
5139,Gerard Gordeau,Kevin Rosier,1,0,11 of 17,0 of 3,64%,0%,11 of 17,0 of 3,...,0 of 0,KO/TKO,1,0:59,No Time Limit,Joao Alberto Barreto,"November 12, 1993","Denver, Colorado, USA",Open Weight Bout,Gerard Gordeau
5140,Ken Shamrock,Patrick Smith,0,0,1 of 1,4 of 8,100%,50%,4 of 4,16 of 20,...,2 of 6,Submission,1,1:49,No Time Limit,Joao Alberto Barreto,"November 12, 1993","Denver, Colorado, USA",Open Weight Bout,Ken Shamrock
5141,Royce Gracie,Art Jimmerson,0,0,0 of 3,0 of 0,0%,0%,4 of 7,0 of 0,...,0 of 0,Submission,1,2:18,No Time Limit,Joao Alberto Barreto,"November 12, 1993","Denver, Colorado, USA",Open Weight Bout,Royce Gracie
5142,Kevin Rosier,Zane Frazier,2,0,15 of 27,12 of 28,55%,42%,38 of 53,13 of 29,...,2 of 2,KO/TKO,1,4:20,No Time Limit,Joao Alberto Barreto,"November 12, 1993","Denver, Colorado, USA",Open Weight Bout,Kevin Rosier
5143,Gerard Gordeau,Teila Tuli,0,0,3 of 5,0 of 1,60%,0%,3 of 5,0 of 1,...,0 of 0,KO/TKO,1,0:26,No Time Limit,Joao Alberto Barreto,"November 12, 1993","Denver, Colorado, USA",Open Weight Bout,Gerard Gordeau

<h5>Dataset columns</h5>

In [92]:
fight = fight_df.columns
print("Colums in the dataset:")
for col in fight:
    print(f" ~{col}")

Colums in the dataset:
 ~R_fighter
 ~B_fighter
 ~R_KD
 ~B_KD
 ~R_SIG_STR.
 ~B_SIG_STR.
 ~R_SIG_STR_pct
 ~B_SIG_STR_pct
 ~R_TOTAL_STR.
 ~B_TOTAL_STR.
 ~R_TD
 ~B_TD
 ~R_TD_pct
 ~B_TD_pct
 ~R_SUB_ATT
 ~B_SUB_ATT
 ~R_PASS
 ~B_PASS
 ~R_REV
 ~B_REV
 ~R_HEAD
 ~B_HEAD
 ~R_BODY
 ~B_BODY
 ~R_LEG
 ~B_LEG
 ~R_DISTANCE
 ~B_DISTANCE
 ~R_CLINCH
 ~B_CLINCH
 ~R_GROUND
 ~B_GROUND
 ~win_by
 ~last_round
 ~last_round_time
 ~Format
 ~Referee
 ~date
 ~location
 ~Fight_type
 ~Winner

<h5>Dataset shape</h5>

In [74]:
fight_df.shape

(5144, 41)

<h5>4th Row</h5>

In [75]:
index4 = fight_df.iloc[3:4]
index4

,R_fighter,B_fighter,R_KD,B_KD,R_SIG_STR.,B_SIG_STR.,R_SIG_STR_pct,B_SIG_STR_pct,R_TOTAL_STR.,B_TOTAL_STR.,...,B_GROUND,win_by,last_round,last_round_time,Format,Referee,date,location,Fight_type,Winner
3,Jimmie Rivera,Petr Yan,0,2,73 of 192,56 of 189,38%,29%,76 of 195,58 of 192,...,4 of 10,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Kevin MacDonald,"June 08, 2019","Chicago, Illinois, USA",Bantamweight Bout,Petr Yan

<h5>Statistical Summary</h5>

In [77]:
fight_df.describe()

,R_KD,B_KD,R_SUB_ATT,B_SUB_ATT,R_PASS,B_PASS,R_REV,B_REV,last_round
count,5144.000000,5144.000000,5144.000000,5144.000000,5144.000000,5144.000000,5144.000000,5144.000000,5144.000000
mean,0.252333,0.180404,0.510886,0.361003,1.401439,0.831260,0.141719,0.134137,2.288297
std,0.523318,0.459646,0.948139,0.809795,2.301587,1.651515,0.427448,0.416798,1.003732
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
75%,0.000000,0.000000,1.000000,0.000000,2.000000,1.000000,0.000000,0.000000,3.000000
max,5.000000,4.000000,10.000000,7.000000,26.000000,14.000000,5.000000,3.000000,5.000000

<h5>Outliers</h5>

The columns in the data set contains outlying values

<h5>Dealing with missing data</h5>

In [83]:
missing = fight_df.isnull()
missing.head(10)

,R_fighter,B_fighter,R_KD,B_KD,R_SIG_STR.,B_SIG_STR.,R_SIG_STR_pct,B_SIG_STR_pct,R_TOTAL_STR.,B_TOTAL_STR.,...,B_GROUND,win_by,last_round,last_round_time,Format,Referee,date,location,Fight_type,Winner
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [84]:
for i in missing.columns.values.tolist():
    print("\n", i)
    print(missing[i].value_counts())

 R_fighter
False    5039
Name: R_fighter, dtype: int64

 B_fighter
False    5039
Name: B_fighter, dtype: int64

 R_KD
False    5039
Name: R_KD, dtype: int64

 B_KD
False    5039
Name: B_KD, dtype: int64

 R_SIG_STR.
False    5039
Name: R_SIG_STR., dtype: int64

 B_SIG_STR.
False    5039
Name: B_SIG_STR., dtype: int64

 R_SIG_STR_pct
False    5039
Name: R_SIG_STR_pct, dtype: int64

 B_SIG_STR_pct
False    5039
Name: B_SIG_STR_pct, dtype: int64

 R_TOTAL_STR.
False    5039
Name: R_TOTAL_STR., dtype: int64

 B_TOTAL_STR.
False    5039
Name: B_TOTAL_STR., dtype: int64

 R_TD
False    5039
Name: R_TD, dtype: int64

 B_TD
False    5039
Name: B_TD, dtype: int64

 R_TD_pct
False    5039
Name: R_TD_pct, dtype: int64

 B_TD_pct
False    5039
Name: B_TD_pct, dtype: int64

 R_SUB_ATT
False    5039
Name: R_SUB_ATT, dtype: int64

 B_SUB_ATT
False    5039
Name: B_SUB_ATT, dtype: int64

 R_PASS
False    5039
Name: R_PASS, dtype: int64

 B_PASS
False    5039
Name: B_PASS, dtype: int64

 R_REV
False    5039
Name: R_REV, dtype: int64

 B_REV
False    5039
Name: B_REV, dtype: int64

 R_HEAD
False    5039
Name: R_HEAD, dtype: int64

 B_HEAD
False    5039
Name: B_HEAD, dtype: int64

 R_BODY
False    5039
Name: R_BODY, dtype: int64

 B_BODY
False    5039
Name: B_BODY, dtype: int64

 R_LEG
False    5039
Name: R_LEG, dtype: int64

 B_LEG
False    5039
Name: B_LEG, dtype: int64

 R_DISTANCE
False    5039
Name: R_DISTANCE, dtype: int64

 B_DISTANCE
False    5039
Name: B_DISTANCE, dtype: int64

 R_CLINCH
False    5039
Name: R_CLINCH, dtype: int64

 B_CLINCH
False    5039
Name: B_CLINCH, dtype: int64

 R_GROUND
False    5039
Name: R_GROUND, dtype: int64

 B_GROUND
False    5039
Name: B_GROUND, dtype: int64

 win_by
False    5039
Name: win_by, dtype: int64

 last_round
False    5039
Name: last_round, dtype: int64

 last_round_time
False    5039
Name: last_round_time, dtype: int64

 Format
False    5039
Name: Format, dtype: int64

 Referee
False    5039
Name: Referee, dtype: int64

 date
False    5039
Name: date, dtype: int64

 location
False    5039
Name: location, dtype: int64

 Fight_type
False    5039
Name: Fight_type, dtype: int64

 Winner
False    5039
Name: Winner, dtype: int64

In [82]:
fight_df.dropna(subset=["Winner", "Referee"], axis=0, inplace=True)

# resetting index after dropping
fight_df.reset_index(drop=True, inplace=True)
fight_df.head(10)

,R_fighter,B_fighter,R_KD,B_KD,R_SIG_STR.,B_SIG_STR.,R_SIG_STR_pct,B_SIG_STR_pct,R_TOTAL_STR.,B_TOTAL_STR.,...,B_GROUND,win_by,last_round,last_round_time,Format,Referee,date,location,Fight_type,Winner
0,Henry Cejudo,Marlon Moraes,0,0,90 of 171,57 of 119,52%,47%,99 of 182,59 of 121,...,1 of 1,KO/TKO,3,4:51,5 Rnd (5-5-5-5-5),Marc Goddard,"June 08, 2019","Chicago, Illinois, USA",UFC Bantamweight Title Bout,Henry Cejudo
1,Valentina Shevchenko,Jessica Eye,1,0,8 of 11,2 of 12,72%,16%,37 of 40,42 of 52,...,0 of 0,KO/TKO,2,0:26,5 Rnd (5-5-5-5-5),Robert Madrigal,"June 08, 2019","Chicago, Illinois, USA",UFC Women's Flyweight Title Bout,Valentina Shevchenko
2,Tony Ferguson,Donald Cerrone,0,0,104 of 200,68 of 185,52%,36%,104 of 200,68 of 185,...,0 of 0,TKO - Doctor's Stoppage,2,5:00,3 Rnd (5-5-5),Dan Miragliotta,"June 08, 2019","Chicago, Illinois, USA",Lightweight Bout,Tony Ferguson
3,Jimmie Rivera,Petr Yan,0,2,73 of 192,56 of 189,38%,29%,76 of 195,58 of 192,...,4 of 10,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Kevin MacDonald,"June 08, 2019","Chicago, Illinois, USA",Bantamweight Bout,Petr Yan
4,Tai Tuivasa,Blagoy Ivanov,0,1,64 of 144,73 of 123,44%,59%,66 of 146,81 of 131,...,6 of 6,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Dan Miragliotta,"June 08, 2019","Chicago, Illinois, USA",Heavyweight Bout,Blagoy Ivanov
5,Tatiana Suarez,Nina Ansaroff,0,0,75 of 142,48 of 99,52%,48%,95 of 166,54 of 105,...,5 of 5,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Robert Madrigal,"June 08, 2019","Chicago, Illinois, USA",Women's Strawweight Bout,Tatiana Suarez
6,Aljamain Sterling,Pedro Munhoz,0,0,174 of 349,105 of 265,49%,39%,175 of 350,108 of 269,...,0 of 0,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Marc Goddard,"June 08, 2019","Chicago, Illinois, USA",Bantamweight Bout,Aljamain Sterling
7,Karolina Kowalkiewicz,Alexa Grasso,0,0,90 of 232,148 of 369,38%,40%,92 of 234,163 of 384,...,0 of 0,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Kevin MacDonald,"June 08, 2019","Chicago, Illinois, USA",Women's Strawweight Bout,Alexa Grasso
8,Ricardo Lamas,Calvin Kattar,0,1,12 of 29,22 of 41,41%,53%,12 of 29,22 of 41,...,4 of 5,KO/TKO,1,4:06,3 Rnd (5-5-5),Dan Miragliotta,"June 08, 2019","Chicago, Illinois, USA",Featherweight Bout,Calvin Kattar
9,Yan Xiaonan,Angela Hill,0,0,94 of 249,71 of 144,37%,49%,105 of 264,78 of 151,...,2 of 2,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Robert Madrigal,"June 08, 2019","Chicago, Illinois, USA",Women's Strawweight Bout,Yan Xiaonan

<h5>Save</h5>

In [94]:
data.to_csv(r"C:\Users\Nnebue Chinedu D\Desktop\dscunilag\Desmond_Nnebue_Week2\processed_raw_total_fight_data.csv")